namespace Recruitment.Gorilla.API.Services;

/// <summary>
/// The one place that decides what a stored CV file name may be, and where a stored file may live.
///
/// Stored names are generated by the server, never chosen by a client: CVUploadController names every
/// upload <c>{Guid}{ext}</c>. Anything else arriving in a request is not a name this server issued, so it
/// is refused before it is saved. Separately, every path built from a stored name is resolved and kept
/// inside the uploads folder, so a bad name that somehow reached the database still cannot point
/// anywhere else.
/// </summary>
public static class UploadPaths
{
    public const string FolderName = "Uploads";

    // The extensions CVUploadController accepts.
    private static readonly HashSet<string> Extensions = new(StringComparer.OrdinalIgnoreCase) { ".pdf", ".docx" };

    /// <summary>
    /// True only for a name the upload endpoint could have produced: a GUID in its standard hyphenated
    /// form, followed by .pdf or .docx. That shape cannot contain a directory separator or a parent
    /// reference, so no further path inspection is needed for a name that passes.
    /// </summary>
    public static bool IsStoredName(string? name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        var extension = Path.GetExtension(name);
        if (!Extensions.Contains(extension)) return false;
        return Guid.TryParseExact(name[..^extension.Length], "D", out _);
    }

    /// <summary>
    /// The full path of a stored file, or null when it would resolve outside the uploads folder.
    /// Callers treat null as "no such file". A name that is not a valid path at all also gives null, so
    /// one bad row cannot turn a delete or an upload into a 500.
    /// </summary>
    public static string? Resolve(string contentRootPath, string storedFileName)
    {
        var root = Path.GetFullPath(Path.Combine(contentRootPath, FolderName));
        string full;
        try
        {
            full = Path.GetFullPath(Path.Combine(root, storedFileName));
        }
        catch (Exception ex) when (ex is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return null;
        }
        // Both come from the same root string, so a legitimate path shares the prefix exactly.
        return full.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal) ? full : null;
    }
}
